export enum NotificationType {
    EVENT_CREATED = 'EVENT_CREATED',
    EVENT_UPDATED = 'EVENT_UPDATED',
    EVENT_DELETED = 'EVENT_DELETED',
    EVENT_INVITATION = 'EVENT_INVITATION',
    EVENT_REMINDER = 'EVENT_REMINDER',
    EVENT_COMMENT = 'EVENT_COMMENT',
    EVENT_LIKE = 'EVENT_LIKE',
    EVENT_SHARE = 'EVENT_SHARE',
    EVENT_RSVP = 'EVENT_RSVP',
    EVENT_CANCELLED = 'EVENT_CANCELLED',
} 